### ISSUE TITLE
Update new techs?

### ISSUE THREAD

**Issue by RustyGun** [Favetti/hadesbotty#56]
Any chance there will be an update to include new techs. Like the Shipment Drone, Delta and Omega Rockets?

**Comment by bonez565** [comment]
I made a pull request to update the omega rocket with lvl10 but I don't see any issues with shipment drone or delta rocket? What exactly is missing?

**Comment by RustyGun** [comment]
Shipment Drone i read on your site like a good kid is shipdrone.

But i still dont seem to be able to get the commands for:

Mining Drone
Delta Rocket and Omega Rocket

Thanks alot for the replies!

**Comment by bonez565** [comment]
I understand, you want what name to use.

Mining Drone is: minedrone
Delta Rocket is: deltarocket
Omega Rocket is: omegarocket

**Comment by RustyGun** [comment]
Yep....

Great bot btw! (Its probably obvious) but I just started using it.

Looking forward to future developments
