### ISSUE TITLE
Techreport @drones 

### ISSUE THREAD

**Issue by cs17sji** [Favetti/hadesbotty#63]
For some reason this command doesnt work anymore. Lately we have had a few more members to join its a merge of 3 hades corps. And many who like to do ws have been given this role. But now any command with @drones role dont work anymore any ideas how to solve this?

**Comment by bonez565** [comment]
it's possible that the resulting report is too long and is being blocked by discords message limit. If you remove some people from the role does it begin to work again?

**Comment by Favetti** [comment]
solved with bonez update to missage limit
