### ISSUE TITLE
Export command

### ISSUE THREAD

**Issue by ThePaladinKing** [Favetti/hadesbotty#64]
What can you export to? An HTML file? On which platform? I've set 777 permissions on one and it doesn't sync. Please... help?

**Comment by Favetti** [comment]
It exports a simple HTML file and is tailored to glitch.com (where i'm hosting it) - you may need to adapt 'dir' and 'url'

**Comment by ThePaladinKing** [comment]
Thank you! I've created a glitch account for my corp here : https://spartanscorp.glitch.me/ but which URL should I use for the bot? I have this one : https://glitch.com/edit/#!/spartanscorp or this one : https://glitch.com/edit/#!/join/e749318e-8764-4c7d-9427-c0e53deb03fe

Thank you so much for your help!

**Comment by Favetti** [comment]
if it's just one Corp I suggest you just invite the official bot there... way easier than keeping a copy running.

**Comment by ThePaladinKing** [comment]
We already have the bot. We want to use the !export command to export our stats into an html sheet like this one : https://hadesbotty.glitch.me/408330194240405516.html and then pull it into a Google Sheet like this one : https://docs.google.com/spreadsheets/d/1d1R8DTcqnrLd9MiWv5qT4sOiMjBoOM5_G8CpNqESNys/edit#gid=629139328

Is that possible?

**Comment by bonez565** [comment]
Simply running the !export command should have the bot reply with a link to the exported data. You can then download the html file via right click or copy it into a spreadsheet.
